/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 08 16:11:32 GMT 2017
 */

package finalprojectB;

import org.junit.Test;
import static org.junit.Assert.*;
import finalprojectB.InetAddressValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class InetAddressValidator_ESTest extends InetAddressValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InetAddressValidator inetAddressValidator0 = new InetAddressValidator();
      boolean boolean0 = inetAddressValidator0.isValidInet4Address("qKRvD[~30+~2J2h%HD");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      InetAddressValidator inetAddressValidator0 = InetAddressValidator.getInstance();
      assertNotNull(inetAddressValidator0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      InetAddressValidator inetAddressValidator0 = new InetAddressValidator();
      boolean boolean0 = inetAddressValidator0.isValid("qKRvD[~30+~2J2h%HD");
      assertFalse(boolean0);
  }
}
